ALTER TABLE tutores ADD COLUMN imagem VARCHAR(255);
ALTER TABLE tutores ADD COLUMN telefone VARCHAR(20);
ALTER TABLE tutores ADD COLUMN cidade VARCHAR(100);
ALTER TABLE tutores ADD COLUMN estado VARCHAR(100);
ALTER TABLE tutores ADD COLUMN sobre TEXT;
